In [5]:
import numpy as np

# 1. 準備數據
# v1, v2, v3 
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])

# 2. 驗證 Rank 和 Determinant
# 合併成3*3的矩陣A
# column_stack 會把向量直的排在一起
A_full = np.column_stack((v1, v2, v3))

print(f"完整矩陣A\n{A_full}")

# 任務A: 計算A_full 的 Rank
rank = np.linalg.matrix_rank(A_full)
print(f"Rank of A: {rank}")

# 任務B: 計算A_full 的 Determinant
det = np.linalg.det(A_full)
print(f"Determinant of A: {det}")

# 檢查邏輯：如果 Rank < 3 且 Det 接近 0，代表 v3 真的沒用（它是多餘的）。

# 3. 找出係數c1, c2
# 目標方程式: v3 = c1*v1 + c2*v2
# 寫成矩陣形式 [v1 v2]@[c1 c2].T = v3
# 所以係數矩陣 (coeefficent matrix) 只有v1 和 v2
matrix_coeff = np.column_stack((v1, v2))

# 任務C: 使用 lstsq 解出 c1, c2
# lstsq 會回傳四個東西，我們只需要第一個 (solution)
solution = np.linalg.lstsq(matrix_coeff, v3, rcond=None)[0]

print(f"Calculated coefficients: {solution}")

# 4. 驗證結果
# 既然算出了c1, c2，我們手動乘回去看看等不等於v3
check_v3 = solution[0] * v1 + solution[1] * v2
print(f"original v3: {v3}")
print(f"reconstructed v3: {check_v3}")

完整矩陣A
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Rank of A: 2
Determinant of A: 0.0
Calculated coefficients: [-1.  2.]
original v3: [7 8 9]
reconstructed v3: [7. 8. 9.]
