In [1]:
import numpy as np

# 1. 準備數據 (5天 x 3資產)
# 這裡隨便設，因為數學性質對任何數據都成立
X_raw = np.array([
    [0.01, 0.02, 0.05],
    [0.02, 0.01, 0.03],
    [-0.01, -0.02, -0.05],
    [0.00, 0.01, 0.01],
    [0.03, 0.03, 0.02]
])

print("原始報酬矩陣 X_raw:\n", X_raw)

# 2. 數據中心化 (Centering)
# Covariance 的定義是 E[(X-mu)(X-mu)^T]。如果不減去平均值，算出來的是二階矩(Moment)而非 Covariance。
# [任務 A]: 算出每一欄(資產)的平均值，然後從 X_raw 扣掉
mu = X_raw.mean(axis=0) # 提示: X_raw.mean(axis=0)
X_centered = X_raw - mu # 提示: X_raw - mu

print("\n中心化後的矩陣 X (確保每個 column 平均為 0):\n", X_centered)

# 3. 手動計算 Covariance Matrix (關鍵步驟)
# 公式： Sigma = (X.T @ X) / (N - 1)
# 這裡的 X.T @ X 就是關鍵！這是一個 Gram Matrix。
N = X_centered.shape[0] # 樣本數 5
Sigma_manual = (X_centered.T @ X_centered) / (N - 1) # 填入公式

print("\n手算 Covariance Matrix:\n", Sigma_manual)

# 4. 驗證是否與 Numpy 黑盒子一致
Sigma_numpy = np.cov(X_raw, rowvar=False)
print("\nNumpy 內建 Covariance Matrix:\n", Sigma_numpy)

# [檢查]: 兩者誤差是否極小？
diff = np.max(np.abs(Sigma_manual - Sigma_numpy))
print(f"\n手算與內建函數的最大誤差: {diff:.10e}")

# 5. 驗證 PSD 性質 (Day 3 重點)
# PSD 的充要條件：所有特徵值 (Eigenvalues) >= 0
# [任務 B]: 計算 Sigma_manual 的特徵值
eigenvalues, _ = np.linalg.eigh(Sigma_manual) # 提示: np.linalg.eigh(Sigma_manual) (eigh 專門用於對稱矩陣，比 eig 更準)

print("\n特徵值 (Eigenvalues):", eigenvalues)

# 判斷：如果有任何一個特徵值是「顯著負數」(考慮浮點誤差，比如 < -1e-10)，那就出大事了。

原始報酬矩陣 X_raw:
 [[ 0.01  0.02  0.05]
 [ 0.02  0.01  0.03]
 [-0.01 -0.02 -0.05]
 [ 0.    0.01  0.01]
 [ 0.03  0.03  0.02]]

中心化後的矩陣 X (確保每個 column 平均為 0):
 [[ 1.73472348e-18  1.00000000e-02  3.80000000e-02]
 [ 1.00000000e-02  1.73472348e-18  1.80000000e-02]
 [-2.00000000e-02 -3.00000000e-02 -6.20000000e-02]
 [-1.00000000e-02  1.73472348e-18 -2.00000000e-03]
 [ 2.00000000e-02  2.00000000e-02  8.00000000e-03]]

手算 Covariance Matrix:
 [[0.00025 0.00025 0.0004 ]
 [0.00025 0.00035 0.0006 ]
 [0.0004  0.0006  0.00142]]

Numpy 內建 Covariance Matrix:
 [[0.00025 0.00025 0.0004 ]
 [0.00025 0.00035 0.0006 ]
 [0.0004  0.0006  0.00142]]

手算與內建函數的最大誤差: 0.0000000000e+00

特徵值 (Eigenvalues): [3.24860062e-05 1.60018812e-04 1.82749518e-03]
